I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
  File "renpy/common/00start.rpy", line 82, in _init_language
    renpy.change_language(language)
  File "game/screens.rpy", line 145, in <module>
    xanchor gui.name_xalig3
AttributeError: 'StoreModule' object has no attribute 'name_xalig3'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\satel\Desktop\renpy-7.3.5-sdk\renpy\bootstrap.py", line 316, in bootstrap
    renpy.main.main()
  File "C:\Users\satel\Desktop\renpy-7.3.5-sdk\renpy\main.py", line 578, in main
    run(restart)
  File "C:\Users\satel\Desktop\renpy-7.3.5-sdk\renpy\main.py", line 75, in run
    renpy.translation.init_translation()
  File "C:\Users\satel\Desktop\renpy-7.3.5-sdk\renpy\translation\__init__.py", line 558, in init_translation
    renpy.store._init_language()  # @UndefinedVariable
  File "renpy/common/00start.rpy", line 82, in _init_language
    renpy.change_language(language)
  File "C:\Users\satel\Desktop\renpy-7.3.5-sdk\renpy\translation\__init__.py", line 638, in change_language
    new_change_language(tl, language)
  File "C:\Users\satel\Desktop\renpy-7.3.5-sdk\renpy\translation\__init__.py", line 604, in new_change_language
    i.apply()
  File "C:\Users\satel\Desktop\renpy-7.3.5-sdk\renpy\ast.py", line 2553, in apply
    value = renpy.python.py_eval(expr)
  File "C:\Users\satel\Desktop\renpy-7.3.5-sdk\renpy\python.py", line 2059, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\satel\Desktop\renpy-7.3.5-sdk\renpy\python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/screens.rpy", line 145, in <module>
    xanchor gui.name_xalig3
AttributeError: 'StoreModule' object has no attribute 'name_xalig3'

Windows-8-6.2.9200
Ren'Py 7.3.5.606
User Interface 0.3.1
Thu Dec 12 21:29:53 2019
