I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/day1.rpy", line 503, in script call
    call questionsEnd from _call_questionsEnd
  File "game/questions/menu.rpy", line 17, in script call
    call pendriveTree
  File "game/questions/menu.rpy", line 42, in script
    menu:
  File "game/questions/menu.rpy", line 47, in <module>
    "Can you tell me what the problem with your brother?" if pendriveSansTree > 0:
NameError: name 'pendriveSansTree' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/day1.rpy", line 503, in script call
    call questionsEnd from _call_questionsEnd
  File "game/questions/menu.rpy", line 17, in script call
    call pendriveTree
  File "game/questions/menu.rpy", line 42, in script
    menu:
  File "C:\Users\satel\Downloads\renpy-6.99.12.2-sdk\renpy\ast.py", line 1609, in execute
    choice = renpy.exports.menu(choices, self.set, args, kwargs, item_arguments)
  File "C:\Users\satel\Downloads\renpy-6.99.12.2-sdk\renpy\exports.py", line 943, in menu
    condition = renpy.python.py_eval(condition)
  File "C:\Users\satel\Downloads\renpy-6.99.12.2-sdk\renpy\python.py", line 1961, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\satel\Downloads\renpy-6.99.12.2-sdk\renpy\python.py", line 1954, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/questions/menu.rpy", line 47, in <module>
    "Can you tell me what the problem with your brother?" if pendriveSansTree > 0:
NameError: name 'pendriveSansTree' is not defined

Windows-8-6.2.9200
Ren'Py 7.2.2.491
UserInterface 0.1.0
Thu May 30 14:04:39 2019
