I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/recipes.rpy", line 61, in script
    define gasterScienceEncyclopedia = true
  File "game/recipes.rpy", line 61, in <module>
    define gasterScienceEncyclopedia = true
NameError: name 'true' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/recipes.rpy", line 61, in script
    define gasterScienceEncyclopedia = true
  File "C:\Users\satel\Downloads\renpy-6.99.12.2-sdk\renpy\ast.py", line 2029, in execute
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\satel\Downloads\renpy-6.99.12.2-sdk\renpy\python.py", line 1954, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/recipes.rpy", line 61, in <module>
    define gasterScienceEncyclopedia = true
NameError: name 'true' is not defined

Windows-8-6.2.9200
Ren'Py 7.2.2.491
User Interface 0.2
Sun Sep 22 17:00:08 2019
