I'm sorry, but an uncaught exception occurred.

While loading <'Image' u'background/tryWithSans/wachingTheDistance.png'>:
  File "game/day1-alt.rpy", line 83, in script
    papyrus "THAT'S FINE"
IOError: Couldn't find file 'background/tryWithSans/wachingTheDistance.png'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/day1-alt.rpy", line 83, in script
    papyrus "THAT'S FINE"
  File "C:\Users\satel\Downloads\renpy-6.99.12.2-sdk\renpy\ast.py", line 1375, in execute
    renpy.exports.with_statement(trans, paired)
  File "C:\Users\satel\Downloads\renpy-6.99.12.2-sdk\renpy\exports.py", line 1578, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\satel\Downloads\renpy-6.99.12.2-sdk\renpy\display\core.py", line 2240, in do_with
    clear=clear)
  File "C:\Users\satel\Downloads\renpy-6.99.12.2-sdk\renpy\display\core.py", line 2690, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\Users\satel\Downloads\renpy-6.99.12.2-sdk\renpy\display\core.py", line 3174, in interact_core
    self.draw_screen(root_widget, fullscreen_video, (not fullscreen_video) or video_frame_drawn)
  File "C:\Users\satel\Downloads\renpy-6.99.12.2-sdk\renpy\display\core.py", line 2086, in draw_screen
    renpy.config.screen_height,
  File "render.pyx", line 516, in renpy.display.render.render_screen
  File "render.pyx", line 244, in renpy.display.render.render
  File "C:\Users\satel\Downloads\renpy-6.99.12.2-sdk\renpy\display\layout.py", line 722, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 151, in renpy.display.render.render
  File "render.pyx", line 244, in renpy.display.render.render
  File "C:\Users\satel\Downloads\renpy-6.99.12.2-sdk\renpy\display\transition.py", line 361, in render
    top = render(self.new_widget, width, height, st, at)
  File "render.pyx", line 151, in renpy.display.render.render
  File "render.pyx", line 244, in renpy.display.render.render
  File "C:\Users\satel\Downloads\renpy-6.99.12.2-sdk\renpy\display\layout.py", line 722, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 151, in renpy.display.render.render
  File "render.pyx", line 244, in renpy.display.render.render
  File "C:\Users\satel\Downloads\renpy-6.99.12.2-sdk\renpy\display\layout.py", line 722, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 151, in renpy.display.render.render
  File "render.pyx", line 244, in renpy.display.render.render
  File "accelerator.pyx", line 110, in renpy.display.accelerator.transform_render
  File "render.pyx", line 244, in renpy.display.render.render
  File "C:\Users\satel\Downloads\renpy-6.99.12.2-sdk\renpy\display\image.py", line 500, in render
    return wrap_render(self.target, width, height, st, at)
  File "C:\Users\satel\Downloads\renpy-6.99.12.2-sdk\renpy\display\image.py", line 306, in wrap_render
    rend = render(child, w, h, st, at)
  File "render.pyx", line 151, in renpy.display.render.render
  File "render.pyx", line 244, in renpy.display.render.render
  File "C:\Users\satel\Downloads\renpy-6.99.12.2-sdk\renpy\display\im.py", line 580, in render
    return cache.get(self, render=True)
  File "C:\Users\satel\Downloads\renpy-6.99.12.2-sdk\renpy\display\im.py", line 266, in get
    surf = image.load()
  File "C:\Users\satel\Downloads\renpy-6.99.12.2-sdk\renpy\display\im.py", line 625, in load
    surf = renpy.display.pgrender.load_image(renpy.loader.load(self.filename), self.filename)
  File "C:\Users\satel\Downloads\renpy-6.99.12.2-sdk\renpy\loader.py", line 576, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'background/tryWithSans/wachingTheDistance.png'.

Windows-8-6.2.9200
Ren'Py 7.2.2.491
User Interface 0.2
Sun Jun 16 00:03:24 2019
